apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mycronjob
  namespace: guest00
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command:
              - date
          restartPolicy: Never