apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: guest00
spec:
  template:
    spec:
      containers:
      - name: time-job
        image: busybox
        command: ["date"]
      restartPolicy: Never
  completions: 5
  backoffLimit: 4