apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guest00-vol
  namespace: guest00
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: hpe-nimble-block
