apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guest00
  namespace: guest00
subjects:
  - kind: ServiceAccount
    name: guest00
    namespace: kube-system
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: pod-read-only