apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
  namespace: guest00
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx01
  template:
    metadata:
      labels:
        app: nginx01
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80